### ISSUE TITLE
Egg doesn't compile on FreeBSD due to missing header include

### ISSUE THREAD

**Issue by sjamaan** [dleslie/posix-semaphore-egg#1]
Hello Dan,

The posix-semaphore egg [fails to compile on FreeBSD](http://salmonella-freebsd-x86-64.call-cc.org/master/clang/freebsd/x86-64/2014/02/28/salmonella-report/install/posix-semaphore.html) due to some missing constants.

As you can see at the Single Unix Spec, these missing constants are defined in [sys/stat.h](http://pubs.opengroup.org/onlinepubs/007908799/xsh/sysstat.h.html). I tested it and adding `#include <sys/stat.h>` fixed the problem.

Cheers,
Peter Bex

**Comment by dleslie** [comment]
Wow, I somehow overlooked this issue.

Fixed in:

ced42d4e660c90bae1436fd1fed92c877dc3d503
